version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"

install:
  - cmd: "%PYTHON%\\python.exe setup.py install"
  - cmd: "%PYTHON%\\python.exe pip install -r requirements.txt"

build: off