name: Black check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: pyratez/black-action@v1.0.2
      with:
          args: ". --line-length 89 --check"
